use crate::core::alf::{AlfManager, AlfType};
use crate::core::transaction_log::TransactionLog;
use crate::parser::TreeNode;
use anyhow::{Context, Result};
use std::path::Path;

pub struct ReportEngine;

pub struct Snapshot {
    pub intent: String,
    pub actor: String,
    pub node_path: String,
    pub file_path: String,
    pub change_summary: String,
    pub timestamp: String,
}

impl ReportEngine {
    pub fn new() -> Self {
        Self
    }

    pub fn generate_markdown_report(&self, project_root: &Path, limit: usize) -> Result<String> {
        let alf = AlfManager::load(project_root)?;
        let tlog = TransactionLog::load(project_root.to_path_buf())?;
        
        let entries = alf.list(limit);
        let mut report = String::new();

        report.push_str("# 📓 GnawTreeWriter Engineering Report\n");
        report.push_str(&format!("Generated at: {}\n\n", chrono::Utc::now().format("%Y-%m-%d %H:%M:%S")));
        report.push_str("## 🛠️ Recent Structural Evolutions\n\n");

        for entry in entries {
            // Only report on automated tool uses or explicit intents with transactions
            if let Some(txn_id) = &entry.transaction_id {
                if let Ok(txn) = tlog.get_transaction(txn_id) {
                    report.push_str(&format!("### 🟢 Transaction: {}\n", &txn_id[..12]));
                    report.push_str("| Layer | Details |\n");
                    report.push_str("| :--- | :--- |\n");
                    
                    // 1. INTENT (The Why)
                    report.push_str(&format!("| **Intent** | {} |\n", entry.message));
                    
                    // 2. STRUCTURE (The What)
                    let node_info = txn.node_path.as_deref().unwrap_or("Root/Multiple");
                    report.push_str(&format!("| **Structure** | Node `{}` in `{}` |\n", node_info, txn.file_path.display()));
                    
                    // 3. ACTOR & TIME
                    report.push_str(&format!("| **Actor** | @{} |\n", entry.actor));
                    report.push_str(&format!("| **Status** | ✅ Verified via TCARV |\n\n"));

                    report.push_str("#### 📝 Structural Change\n");
                    report.push_str("```rust\n"); // We assume rust for the report or detect from extension
                    report.push_str(&txn.description);
                    report.push_str("\n```\n\n---\n\n");
                }
            } else if entry.entry_type == AlfType::Intent || entry.entry_type == AlfType::Risk {
                // Log high-level intents even without transactions
                report.push_str(&format!("### 🎯 Strategic Intent (@{}\n", entry.actor));
                report.push_str(&format!("> {}\n\n", entry.message));
                if !entry.tags.is_empty() {
                    report.push_str(&format!("*Tags: {}*\n", entry.tags.join(", ")));
                }
                report.push_str("\n---\n\n");
            }
        }

        report.push_str("\n*This report was automatically generated by the GnawTreeWriter ReportEngine.*\n");
        Ok(report)
    }
}
